kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.25.3
controlPlaneEndpoint: "dna.ocf.io:6443"
networking:
  podSubnet: 10.244.0.0/16,2607:f140:8801:1::/64
  serviceSubnet: 10.96.0.0/16,2607:f140:8801:2::/112
apiServer:
  certSANs:
  - dna.ocf.io
  - dna.ocf.berkeley.edu
clusterName: ocf-dna
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
staticPodPath: "/etc/kubernetes/manifests"
clusterDNS:
- 10.96.0.10
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: "unix:///var/run/crio/crio.sock"
skipPhases:
  - addon/kube-proxy
  - addon/coredns
